// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/auth/v1/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaRequest) Reset() {
	*x = GetCaptchaRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaRequest) ProtoMessage() {}

func (x *GetCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaRequest.ProtoReflect.Descriptor instead.
func (*GetCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

type GetCaptchaResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Code          int32                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TraceId       string                   `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Data          *GetCaptchaResponse_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaResponse) Reset() {
	*x = GetCaptchaResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaResponse) ProtoMessage() {}

func (x *GetCaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaResponse.ProtoReflect.Descriptor instead.
func (*GetCaptchaResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetCaptchaResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCaptchaResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetCaptchaResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetCaptchaResponse) GetData() *GetCaptchaResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendEmailCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	CaptchaKey    string                 `protobuf:"bytes,2,opt,name=captcha_key,json=captchaKey,proto3" json:"captcha_key,omitempty"`
	CaptchaValue  string                 `protobuf:"bytes,3,opt,name=captcha_value,json=captchaValue,proto3" json:"captcha_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailCodeRequest) Reset() {
	*x = SendEmailCodeRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailCodeRequest) ProtoMessage() {}

func (x *SendEmailCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailCodeRequest.ProtoReflect.Descriptor instead.
func (*SendEmailCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SendEmailCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendEmailCodeRequest) GetCaptchaKey() string {
	if x != nil {
		return x.CaptchaKey
	}
	return ""
}

func (x *SendEmailCodeRequest) GetCaptchaValue() string {
	if x != nil {
		return x.CaptchaValue
	}
	return ""
}

type SendEmailCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailCodeResponse) Reset() {
	*x = SendEmailCodeResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailCodeResponse) ProtoMessage() {}

func (x *SendEmailCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailCodeResponse.ProtoReflect.Descriptor instead.
func (*SendEmailCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SendEmailCodeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendEmailCodeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendEmailCodeResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type RegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Age            int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Password       string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Code           string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	TurnstileToken string                 `protobuf:"bytes,6,opt,name=turnstile_token,json=turnstileToken,proto3" json:"turnstile_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterRequest) GetTurnstileToken() string {
	if x != nil {
		return x.TurnstileToken
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RegisterResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Data          *LoginResponse_Data    `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *LoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LoginResponse) GetData() *LoginResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetWebAuthnRegistrationOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebAuthnRegistrationOptionsRequest) Reset() {
	*x = GetWebAuthnRegistrationOptionsRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebAuthnRegistrationOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebAuthnRegistrationOptionsRequest) ProtoMessage() {}

func (x *GetWebAuthnRegistrationOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebAuthnRegistrationOptionsRequest.ProtoReflect.Descriptor instead.
func (*GetWebAuthnRegistrationOptionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

type GetWebAuthnRegistrationOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	OptionsJson   string                 `protobuf:"bytes,3,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	TraceId       string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebAuthnRegistrationOptionsResponse) Reset() {
	*x = GetWebAuthnRegistrationOptionsResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebAuthnRegistrationOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebAuthnRegistrationOptionsResponse) ProtoMessage() {}

func (x *GetWebAuthnRegistrationOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebAuthnRegistrationOptionsResponse.ProtoReflect.Descriptor instead.
func (*GetWebAuthnRegistrationOptionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *GetWebAuthnRegistrationOptionsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetWebAuthnRegistrationOptionsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetWebAuthnRegistrationOptionsResponse) GetOptionsJson() string {
	if x != nil {
		return x.OptionsJson
	}
	return ""
}

func (x *GetWebAuthnRegistrationOptionsResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type VerifyWebAuthnRegistrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CredentialJson string                 `protobuf:"bytes,1,opt,name=credential_json,json=credentialJson,proto3" json:"credential_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyWebAuthnRegistrationRequest) Reset() {
	*x = VerifyWebAuthnRegistrationRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWebAuthnRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWebAuthnRegistrationRequest) ProtoMessage() {}

func (x *VerifyWebAuthnRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWebAuthnRegistrationRequest.ProtoReflect.Descriptor instead.
func (*VerifyWebAuthnRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyWebAuthnRegistrationRequest) GetCredentialJson() string {
	if x != nil {
		return x.CredentialJson
	}
	return ""
}

type VerifyWebAuthnRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWebAuthnRegistrationResponse) Reset() {
	*x = VerifyWebAuthnRegistrationResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWebAuthnRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWebAuthnRegistrationResponse) ProtoMessage() {}

func (x *VerifyWebAuthnRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWebAuthnRegistrationResponse.ProtoReflect.Descriptor instead.
func (*VerifyWebAuthnRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyWebAuthnRegistrationResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VerifyWebAuthnRegistrationResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *VerifyWebAuthnRegistrationResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetWebAuthnLoginOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TempToken     string                 `protobuf:"bytes,1,opt,name=temp_token,json=tempToken,proto3" json:"temp_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebAuthnLoginOptionsRequest) Reset() {
	*x = GetWebAuthnLoginOptionsRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebAuthnLoginOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebAuthnLoginOptionsRequest) ProtoMessage() {}

func (x *GetWebAuthnLoginOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebAuthnLoginOptionsRequest.ProtoReflect.Descriptor instead.
func (*GetWebAuthnLoginOptionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *GetWebAuthnLoginOptionsRequest) GetTempToken() string {
	if x != nil {
		return x.TempToken
	}
	return ""
}

type GetWebAuthnLoginOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	OptionsJson   string                 `protobuf:"bytes,3,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	TraceId       string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebAuthnLoginOptionsResponse) Reset() {
	*x = GetWebAuthnLoginOptionsResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebAuthnLoginOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebAuthnLoginOptionsResponse) ProtoMessage() {}

func (x *GetWebAuthnLoginOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebAuthnLoginOptionsResponse.ProtoReflect.Descriptor instead.
func (*GetWebAuthnLoginOptionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *GetWebAuthnLoginOptionsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetWebAuthnLoginOptionsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetWebAuthnLoginOptionsResponse) GetOptionsJson() string {
	if x != nil {
		return x.OptionsJson
	}
	return ""
}

func (x *GetWebAuthnLoginOptionsResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type VerifyWebAuthnLoginRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TempToken      string                 `protobuf:"bytes,1,opt,name=temp_token,json=tempToken,proto3" json:"temp_token,omitempty"`
	CredentialJson string                 `protobuf:"bytes,2,opt,name=credential_json,json=credentialJson,proto3" json:"credential_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyWebAuthnLoginRequest) Reset() {
	*x = VerifyWebAuthnLoginRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWebAuthnLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWebAuthnLoginRequest) ProtoMessage() {}

func (x *VerifyWebAuthnLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWebAuthnLoginRequest.ProtoReflect.Descriptor instead.
func (*VerifyWebAuthnLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyWebAuthnLoginRequest) GetTempToken() string {
	if x != nil {
		return x.TempToken
	}
	return ""
}

func (x *VerifyWebAuthnLoginRequest) GetCredentialJson() string {
	if x != nil {
		return x.CredentialJson
	}
	return ""
}

type VerifyWebAuthnLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWebAuthnLoginResponse) Reset() {
	*x = VerifyWebAuthnLoginResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWebAuthnLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWebAuthnLoginResponse) ProtoMessage() {}

func (x *VerifyWebAuthnLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWebAuthnLoginResponse.ProtoReflect.Descriptor instead.
func (*VerifyWebAuthnLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *VerifyWebAuthnLoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VerifyWebAuthnLoginResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *VerifyWebAuthnLoginResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{16}
}

type GetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Data          *GetMeResponse_Data    `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *GetMeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetMeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetMeResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetMeResponse) GetData() *GetMeResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetCaptchaResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaKey    string                 `protobuf:"bytes,1,opt,name=captcha_key,json=captchaKey,proto3" json:"captcha_key,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaResponse_Data) Reset() {
	*x = GetCaptchaResponse_Data{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaResponse_Data) ProtoMessage() {}

func (x *GetCaptchaResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaResponse_Data.ProtoReflect.Descriptor instead.
func (*GetCaptchaResponse_Data) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetCaptchaResponse_Data) GetCaptchaKey() string {
	if x != nil {
		return x.CaptchaKey
	}
	return ""
}

func (x *GetCaptchaResponse_Data) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type LoginResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Require_2Fa   bool                   `protobuf:"varint,1,opt,name=require_2fa,json=require2fa,proto3" json:"require_2fa,omitempty"`
	Setup_2Fa     bool                   `protobuf:"varint,2,opt,name=setup_2fa,json=setup2fa,proto3" json:"setup_2fa,omitempty"`
	TempToken     string                 `protobuf:"bytes,3,opt,name=temp_token,json=tempToken,proto3" json:"temp_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse_Data) Reset() {
	*x = LoginResponse_Data{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_Data) ProtoMessage() {}

func (x *LoginResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_Data.ProtoReflect.Descriptor instead.
func (*LoginResponse_Data) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{7, 0}
}

func (x *LoginResponse_Data) GetRequire_2Fa() bool {
	if x != nil {
		return x.Require_2Fa
	}
	return false
}

func (x *LoginResponse_Data) GetSetup_2Fa() bool {
	if x != nil {
		return x.Setup_2Fa
	}
	return false
}

func (x *LoginResponse_Data) GetTempToken() string {
	if x != nil {
		return x.TempToken
	}
	return ""
}

type GetMeResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse_Data) Reset() {
	*x = GetMeResponse_Data{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse_Data) ProtoMessage() {}

func (x *GetMeResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse_Data.ProtoReflect.Descriptor instead.
func (*GetMeResponse_Data) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{17, 0}
}

func (x *GetMeResponse_Data) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetMeResponse_Data) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_auth_v1_auth_proto protoreflect.FileDescriptor

const file_proto_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18proto/auth/v1/auth.proto\x12\x12foolsignup.auth.v1\"\x13\n" +
	"\x11GetCaptchaRequest\"\xd5\x01\n" +
	"\x12GetCaptchaResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12?\n" +
	"\x04data\x18\x04 \x01(\v2+.foolsignup.auth.v1.GetCaptchaResponse.DataR\x04data\x1a=\n" +
	"\x04Data\x12\x1f\n" +
	"\vcaptcha_key\x18\x01 \x01(\tR\n" +
	"captchaKey\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"r\n" +
	"\x14SendEmailCodeRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1f\n" +
	"\vcaptcha_key\x18\x02 \x01(\tR\n" +
	"captchaKey\x12#\n" +
	"\rcaptcha_value\x18\x03 \x01(\tR\fcaptchaValue\"X\n" +
	"\x15SendEmailCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\"\xae\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12'\n" +
	"\x0fturnstile_token\x18\x06 \x01(\tR\x0eturnstileToken\"S\n" +
	"\x10RegisterResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xf1\x01\n" +
	"\rLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12:\n" +
	"\x04data\x18\x04 \x01(\v2&.foolsignup.auth.v1.LoginResponse.DataR\x04data\x1ac\n" +
	"\x04Data\x12\x1f\n" +
	"\vrequire_2fa\x18\x01 \x01(\bR\n" +
	"require2fa\x12\x1b\n" +
	"\tsetup_2fa\x18\x02 \x01(\bR\bsetup2fa\x12\x1d\n" +
	"\n" +
	"temp_token\x18\x03 \x01(\tR\ttempToken\"'\n" +
	"%GetWebAuthnRegistrationOptionsRequest\"\x8c\x01\n" +
	"&GetWebAuthnRegistrationOptionsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\foptions_json\x18\x03 \x01(\tR\voptionsJson\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\"L\n" +
	"!VerifyWebAuthnRegistrationRequest\x12'\n" +
	"\x0fcredential_json\x18\x01 \x01(\tR\x0ecredentialJson\"e\n" +
	"\"VerifyWebAuthnRegistrationResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\"?\n" +
	"\x1eGetWebAuthnLoginOptionsRequest\x12\x1d\n" +
	"\n" +
	"temp_token\x18\x01 \x01(\tR\ttempToken\"\x85\x01\n" +
	"\x1fGetWebAuthnLoginOptionsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\foptions_json\x18\x03 \x01(\tR\voptionsJson\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\"d\n" +
	"\x1aVerifyWebAuthnLoginRequest\x12\x1d\n" +
	"\n" +
	"temp_token\x18\x01 \x01(\tR\ttempToken\x12'\n" +
	"\x0fcredential_json\x18\x02 \x01(\tR\x0ecredentialJson\"^\n" +
	"\x1bVerifyWebAuthnLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\"\x0e\n" +
	"\fGetMeRequest\"\xc6\x01\n" +
	"\rGetMeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12:\n" +
	"\x04data\x18\x04 \x01(\v2&.foolsignup.auth.v1.GetMeResponse.DataR\x04data\x1a8\n" +
	"\x04Data\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email2\xe8\a\n" +
	"\vAuthService\x12[\n" +
	"\n" +
	"GetCaptcha\x12%.foolsignup.auth.v1.GetCaptchaRequest\x1a&.foolsignup.auth.v1.GetCaptchaResponse\x12d\n" +
	"\rSendEmailCode\x12(.foolsignup.auth.v1.SendEmailCodeRequest\x1a).foolsignup.auth.v1.SendEmailCodeResponse\x12U\n" +
	"\bRegister\x12#.foolsignup.auth.v1.RegisterRequest\x1a$.foolsignup.auth.v1.RegisterResponse\x12L\n" +
	"\x05Login\x12 .foolsignup.auth.v1.LoginRequest\x1a!.foolsignup.auth.v1.LoginResponse\x12L\n" +
	"\x05GetMe\x12 .foolsignup.auth.v1.GetMeRequest\x1a!.foolsignup.auth.v1.GetMeResponse\x12\x97\x01\n" +
	"\x1eGetWebAuthnRegistrationOptions\x129.foolsignup.auth.v1.GetWebAuthnRegistrationOptionsRequest\x1a:.foolsignup.auth.v1.GetWebAuthnRegistrationOptionsResponse\x12\x8b\x01\n" +
	"\x1aVerifyWebAuthnRegistration\x125.foolsignup.auth.v1.VerifyWebAuthnRegistrationRequest\x1a6.foolsignup.auth.v1.VerifyWebAuthnRegistrationResponse\x12\x82\x01\n" +
	"\x17GetWebAuthnLoginOptions\x122.foolsignup.auth.v1.GetWebAuthnLoginOptionsRequest\x1a3.foolsignup.auth.v1.GetWebAuthnLoginOptionsResponse\x12v\n" +
	"\x13VerifyWebAuthnLogin\x12..foolsignup.auth.v1.VerifyWebAuthnLoginRequest\x1a/.foolsignup.auth.v1.VerifyWebAuthnLoginResponseB+Z)foolsignup-api/internal/pb/auth/v1;authpbb\x06proto3"

var (
	file_proto_auth_v1_auth_proto_rawDescOnce sync.Once
	file_proto_auth_v1_auth_proto_rawDescData []byte
)

func file_proto_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_v1_auth_proto_rawDesc), len(file_proto_auth_v1_auth_proto_rawDesc)))
	})
	return file_proto_auth_v1_auth_proto_rawDescData
}

var file_proto_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_auth_v1_auth_proto_goTypes = []any{
	(*GetCaptchaRequest)(nil),                      // 0: foolsignup.auth.v1.GetCaptchaRequest
	(*GetCaptchaResponse)(nil),                     // 1: foolsignup.auth.v1.GetCaptchaResponse
	(*SendEmailCodeRequest)(nil),                   // 2: foolsignup.auth.v1.SendEmailCodeRequest
	(*SendEmailCodeResponse)(nil),                  // 3: foolsignup.auth.v1.SendEmailCodeResponse
	(*RegisterRequest)(nil),                        // 4: foolsignup.auth.v1.RegisterRequest
	(*RegisterResponse)(nil),                       // 5: foolsignup.auth.v1.RegisterResponse
	(*LoginRequest)(nil),                           // 6: foolsignup.auth.v1.LoginRequest
	(*LoginResponse)(nil),                          // 7: foolsignup.auth.v1.LoginResponse
	(*GetWebAuthnRegistrationOptionsRequest)(nil),  // 8: foolsignup.auth.v1.GetWebAuthnRegistrationOptionsRequest
	(*GetWebAuthnRegistrationOptionsResponse)(nil), // 9: foolsignup.auth.v1.GetWebAuthnRegistrationOptionsResponse
	(*VerifyWebAuthnRegistrationRequest)(nil),      // 10: foolsignup.auth.v1.VerifyWebAuthnRegistrationRequest
	(*VerifyWebAuthnRegistrationResponse)(nil),     // 11: foolsignup.auth.v1.VerifyWebAuthnRegistrationResponse
	(*GetWebAuthnLoginOptionsRequest)(nil),         // 12: foolsignup.auth.v1.GetWebAuthnLoginOptionsRequest
	(*GetWebAuthnLoginOptionsResponse)(nil),        // 13: foolsignup.auth.v1.GetWebAuthnLoginOptionsResponse
	(*VerifyWebAuthnLoginRequest)(nil),             // 14: foolsignup.auth.v1.VerifyWebAuthnLoginRequest
	(*VerifyWebAuthnLoginResponse)(nil),            // 15: foolsignup.auth.v1.VerifyWebAuthnLoginResponse
	(*GetMeRequest)(nil),                           // 16: foolsignup.auth.v1.GetMeRequest
	(*GetMeResponse)(nil),                          // 17: foolsignup.auth.v1.GetMeResponse
	(*GetCaptchaResponse_Data)(nil),                // 18: foolsignup.auth.v1.GetCaptchaResponse.Data
	(*LoginResponse_Data)(nil),                     // 19: foolsignup.auth.v1.LoginResponse.Data
	(*GetMeResponse_Data)(nil),                     // 20: foolsignup.auth.v1.GetMeResponse.Data
}
var file_proto_auth_v1_auth_proto_depIdxs = []int32{
	18, // 0: foolsignup.auth.v1.GetCaptchaResponse.data:type_name -> foolsignup.auth.v1.GetCaptchaResponse.Data
	19, // 1: foolsignup.auth.v1.LoginResponse.data:type_name -> foolsignup.auth.v1.LoginResponse.Data
	20, // 2: foolsignup.auth.v1.GetMeResponse.data:type_name -> foolsignup.auth.v1.GetMeResponse.Data
	0,  // 3: foolsignup.auth.v1.AuthService.GetCaptcha:input_type -> foolsignup.auth.v1.GetCaptchaRequest
	2,  // 4: foolsignup.auth.v1.AuthService.SendEmailCode:input_type -> foolsignup.auth.v1.SendEmailCodeRequest
	4,  // 5: foolsignup.auth.v1.AuthService.Register:input_type -> foolsignup.auth.v1.RegisterRequest
	6,  // 6: foolsignup.auth.v1.AuthService.Login:input_type -> foolsignup.auth.v1.LoginRequest
	16, // 7: foolsignup.auth.v1.AuthService.GetMe:input_type -> foolsignup.auth.v1.GetMeRequest
	8,  // 8: foolsignup.auth.v1.AuthService.GetWebAuthnRegistrationOptions:input_type -> foolsignup.auth.v1.GetWebAuthnRegistrationOptionsRequest
	10, // 9: foolsignup.auth.v1.AuthService.VerifyWebAuthnRegistration:input_type -> foolsignup.auth.v1.VerifyWebAuthnRegistrationRequest
	12, // 10: foolsignup.auth.v1.AuthService.GetWebAuthnLoginOptions:input_type -> foolsignup.auth.v1.GetWebAuthnLoginOptionsRequest
	14, // 11: foolsignup.auth.v1.AuthService.VerifyWebAuthnLogin:input_type -> foolsignup.auth.v1.VerifyWebAuthnLoginRequest
	1,  // 12: foolsignup.auth.v1.AuthService.GetCaptcha:output_type -> foolsignup.auth.v1.GetCaptchaResponse
	3,  // 13: foolsignup.auth.v1.AuthService.SendEmailCode:output_type -> foolsignup.auth.v1.SendEmailCodeResponse
	5,  // 14: foolsignup.auth.v1.AuthService.Register:output_type -> foolsignup.auth.v1.RegisterResponse
	7,  // 15: foolsignup.auth.v1.AuthService.Login:output_type -> foolsignup.auth.v1.LoginResponse
	17, // 16: foolsignup.auth.v1.AuthService.GetMe:output_type -> foolsignup.auth.v1.GetMeResponse
	9,  // 17: foolsignup.auth.v1.AuthService.GetWebAuthnRegistrationOptions:output_type -> foolsignup.auth.v1.GetWebAuthnRegistrationOptionsResponse
	11, // 18: foolsignup.auth.v1.AuthService.VerifyWebAuthnRegistration:output_type -> foolsignup.auth.v1.VerifyWebAuthnRegistrationResponse
	13, // 19: foolsignup.auth.v1.AuthService.GetWebAuthnLoginOptions:output_type -> foolsignup.auth.v1.GetWebAuthnLoginOptionsResponse
	15, // 20: foolsignup.auth.v1.AuthService.VerifyWebAuthnLogin:output_type -> foolsignup.auth.v1.VerifyWebAuthnLoginResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_auth_v1_auth_proto_init() }
func file_proto_auth_v1_auth_proto_init() {
	if File_proto_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_v1_auth_proto_rawDesc), len(file_proto_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_v1_auth_proto = out.File
	file_proto_auth_v1_auth_proto_goTypes = nil
	file_proto_auth_v1_auth_proto_depIdxs = nil
}
